name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          persist-credentials: false
          lfs: true

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: '20'

      - name: Build Project
        run: |
          npm ci
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          folder: output
          clean: true
          single-commit: true