name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          lfs: true
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version: '21'

      - name: Build Project
        run: |
          npm ci
          npm run build

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          commit_message: "Automated update based on the latest build"
          branch: main
          file_pattern: "output/**"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.6.4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          folder: output
          clean: true
          single-commit: true
